name: Build Google-Drive-CI-CD

on:
  push:
    branches:
      - master
#  workflow_dispatch:
#    inputs:
#      google_drive:
#        description: 'Upload apk to google drive'
#        required: false
#        type: boolean

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  development:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Archive APK
        uses: actions/upload-artifact@v2
        with:
          name: app-debug.apk
          path: app/build/outputs/apk/debug/app-debug.apk
      - name: Upload apk to Google Drive
        uses: logickoder/google-drive-upload@test
        with:
          credentials: ${{ secrets.GCP_CREDENTIAL }}
          filename: "app/build/outputs/apk/debug/app-debug.apk"
          folderID: ${{ secrets.DRIVE_FOLDER_ID }}
          overwrite: "true"
         
